on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Build and Start Server
        run: |
          npm run build
          npm run start &
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          PORT: 3000

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          # Ensure these JSON files are also in /server/tests/
          # If they are in the root /tests, use ../tests/collection.json
          newman run ./tests/collection.json \
          -e ./tests/environment.json \
          --env-var "jwt_secret=${{ secrets.JWT_SECRET }}" \
          --env-var "baseUrl=http://localhost:3000"
